#!/bin/sh
# $Id$
# elvis: myanimelist	-- Search MyAnimeList for anime, manga, characters, people, and users (myanimelist.net)
# Adapted from `debpackages` elvis.
. surfraw || exit 1

w3_config_hook ()
{
	def SURFRAW_myanimelist_search all
}

w3_usage_hook ()
{
	cat <<EOF
Usage: $w3_argv0 [options] [search words]...
Description:
  Search MyAnimeList for anime, manga, characters, people, and users (myanimelist.net)
Local options:
  -search=                      Field to search
	  all           |       All of the available search options (default)
          anime         |       Anime TV shows, movies, OVAs, etc.
          manga         |       Manga, [light] novels, etc.
          character     |       Characters from anime and manga only
          people        |       Directors, voice actors, etc.
          users         |       MyAnimeList users
EOF
	w3_global_usage
}

w3_parse_option_hook ()
{
	opt="$1"
	optarg="$2"
	case "$opt" in
		-search=*) setopt SURFRAW_myanimelist_search $optarg ;;
		*) return 1 ;;
	esac
	return 0
}


w3_config
w3_parse_args "$@"
# w3_args now contains a list of arguments

# MyAnimeList doesn't have a dedicated search page.
default_search_url='https://myanimelist.net/search/all?q=default'
base_url='https://myanimelist.net'

if test -z "$w3_args"; then
	w3_browse_url "$default_search_url"
else
	escaped_args=$(w3_url_of_arg $w3_args)
	case "$SURFRAW_myanimelist_search" in
		all) search_type='search/all' ;;
		anime|manga|character|people|users) search_type="$SURFRAW_myanimelist_search.php" ;;
		# Be more lenient with search types.
		characters) search_type='character.php' ;;
		user) search_type='users.php' ;;
		*) err "Unknown search type" ;;
	esac
	# The search URLs for MyAnimeList are all over the place.
	# They aren't all under 'myanimelist.net/search'.
	url="$base_url/$search_type"
	url="$url?q=$escaped_args"

	w3_browse_url "$url"
fi
